### ISSUE TITLE
Some videos will not play.

### ISSUE THREAD

**Issue by techprowizard** [MrKrabat/plugin.video.crunchyroll#11]
Some videos will not play. It tries to load then just goes back the video selection screen.
Log is attached.
[kodi.log](https://github.com/MrKrabat/plugin.video.crunchyroll/files/2435218/kodi.log)

**Comment by robofunk** [comment]
You both probably want to update. Only adaptive quality is now supported.

**Comment by oomek** [comment]
You are right, it's fixed in 3.1.1 but for some reason your repo doesn't work, I've had to update manually.

**Comment by MrKrabat** [comment]
This addon is in no kodi repository due to legal actions of crunchyroll against the other addon that existed before.

**Comment by oomek** [comment]
I'm an idiot. I copied
https://github.com/MrKrabat/plugin.video.crunchyroll
and added it to Kodi in the file manager hoping I'll find a repo there. Nevermind, thanks for the fix.

**Comment by techprowizard** [comment]
well, maybe it was a fluke yesterday or something, because now everything looks to be working again.
