### ISSUE TITLE
Dependancies not met: Please contact author

### ISSUE THREAD

**Issue by AJRubenstein** [MrKrabat/plugin.video.crunchyroll#15]
My sincere apologies, I'm having all sorts of strife with my Kodi installation at the moment so the log file will be a bit of a mess of it complaining it can't access SMB shares that were working this morning... I digress. I've been trying to install this plugin - and I keep getting the Dependances not met: Please Contact Author message whenever I try and "install from .zip" using the Kodi Raspberry Pi app in OpenElec.

Please find attached my haphazard attempt at giving you the log file at the bottom of this message.

Thanks!

00:03:13 193.516907 T:1967697920   ERROR: Previous line repeats 2 times.
00:03:13 193.517136 T:1967697920   ERROR: GetDirectory - Error getting smb://10.                                                0.0.10/TV/
00:03:13 193.520645 T:1967697920   ERROR: CGUIMediaWindow::GetDirectory(smb://10                                                .0.0.10/TV/) failed
00:03:13 193.569275 T:1620292672  NOTICE: Thread BackgroundLoader start, auto de                                                lete: false
00:03:38 218.118210 T:1793061952  NOTICE: Previous line repeats 1 times.
00:03:38 218.118454 T:1793061952   ERROR: CAddonInstallJob[plugin.video.crunchyr                                                oll]: dependency check failed
00:03:38 218.331604 T:1620292672  NOTICE: Thread BackgroundLoader start, auto de                                                lete: false
00:04:48 288.291626 T:1967697920  NOTICE: Samba is idle. Closing the remaining c                                                onnections
OpenELEC:~/.kodi/temp # cat kodi.log
ï»¿00:00:08   8.188032 T:1967697920  NOTICE: special://profile/ is mapped to: special://masterprofile/
00:00:08   8.188279 T:1967697920  NOTICE: -----------------------------------------------------------------------
00:00:08   8.188372 T:1967697920  NOTICE: Starting Kodi (15.2 Git:02e7013). Platform: Linux ARM 32-bit
00:00:08   8.188444 T:1967697920  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
00:00:08   8.188520 T:1967697920  NOTICE: Kodi compiled Mar  1 2016 by GCC 4.9.3 for Linux ARM 32-bit version 4.1.18 (262418)
00:00:08   8.188900 T:1967697920  NOTICE: Running on OpenELEC (official) - Version: 6.0.3, kernel: Linux ARM 32-bit version 4.1.18
00:00:08   8.188983 T:1967697920  NOTICE: FFmpeg version: 2.6.4
00:00:08   8.189043 T:1967697920  NOTICE: WARNING: unsupported ffmpeg version detected
00:00:08   8.189105 T:1967697920  NOTICE: Host CPU: ARMv7 Processor rev 5 (v7l), 4 cores available
00:00:08   8.189162 T:1967697920  NOTICE: ARM Features: Neon enabled
00:00:08   8.189222 T:1967697920  NOTICE: special://xbmc/ is mapped to: /usr/share/kodi
00:00:08   8.189282 T:1967697920  NOTICE: special://xbmcbin/ is mapped to: /usr/lib/kodi
00:00:08   8.189342 T:1967697920  NOTICE: special://masterprofile/ is mapped to: /storage/.kodi/userdata
00:00:08   8.189404 T:1967697920  NOTICE: special://home/ is mapped to: /storage/.kodi
00:00:08   8.189466 T:1967697920  NOTICE: special://temp/ is mapped to: /storage/.kodi/temp
00:00:08   8.189626 T:1967697920  NOTICE: The executable running is: /usr/lib/kodi/kodi.bin
00:00:08   8.189735 T:1967697920  NOTICE: Local hostname: OpenELEC
00:00:08   8.189802 T:1967697920  NOTICE: Log File is located: /storage/.kodi/temp/kodi.log
00:00:08   8.196603 T:1967697920  NOTICE: -----------------------------------------------------------------------
00:00:08   8.320966 T:1967697920   ERROR: DBus: Error org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.UPower was not provided by any .service files
00:00:08   8.334002 T:1967697920  NOTICE: load settings...
00:00:08   8.444740 T:1967682624  NOTICE: Thread FDEventMonitor start, auto delete: false
00:00:08   8.483007 T:1967697920  NOTICE: Found 1 Lists of Devices
00:00:08   8.483187 T:1967697920  NOTICE: Enumerated PI devices:
00:00:08   8.483257 T:1967697920  NOTICE:     Device 1
00:00:08   8.483914 T:1967697920  NOTICE:         m_deviceName      : HDMI
00:00:08   8.484028 T:1967697920  NOTICE:         m_displayName     : HDMI
00:00:08   8.484094 T:1967697920  NOTICE:         m_displayNameExtra:
00:00:08   8.484155 T:1967697920  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
00:00:08   8.484215 T:1967697920  NOTICE:         m_channels        : FL,FR
00:00:08   8.484278 T:1967697920  NOTICE:         m_sampleRates     : 8000,11025,16000,22050,24000,32000,44100,48000,88200,96000,176400,192000
00:00:08   8.484342 T:1967697920  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP,AE_FMT_AC3,AE_FMT_DTS,AE_FMT_EAC3
00:00:08   8.484433 T:1967697920  NOTICE:     Device 2
00:00:08   8.484554 T:1967697920  NOTICE:         m_deviceName      : Analogue
00:00:08   8.484618 T:1967697920  NOTICE:         m_displayName     : Analogue
00:00:08   8.484678 T:1967697920  NOTICE:         m_displayNameExtra:
00:00:08   8.484738 T:1967697920  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
00:00:08   8.484796 T:1967697920  NOTICE:         m_channels        : FL,FR
00:00:08   8.484855 T:1967697920  NOTICE:         m_sampleRates     : 48000
00:00:08   8.484916 T:1967697920  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP
00:00:08   8.484977 T:1967697920  NOTICE:     Device 3
00:00:08   8.485084 T:1967697920  NOTICE:         m_deviceName      : Both
00:00:08   8.485147 T:1967697920  NOTICE:         m_displayName     : HDMI and Analogue
00:00:08   8.485206 T:1967697920  NOTICE:         m_displayNameExtra:
00:00:08   8.485264 T:1967697920  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
00:00:08   8.485373 T:1967697920  NOTICE:         m_channels        : FL,FR
00:00:08   8.485475 T:1967697920  NOTICE:         m_sampleRates     : 48000
00:00:08   8.485557 T:1967697920  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP
00:00:08   8.518037 T:1967697920  NOTICE: Loaded settings file from special://xbmc/system/advancedsettings.xml
00:00:08   8.518468 T:1967697920  NOTICE: Contents of special://xbmc/system/advancedsettings.xml are...
                                            <?xml version="1.0" encoding="UTF-8" ?>
                                            <advancedsettings>
                                              <showexitbutton>false</showexitbutton>
                                              <fanartres>720</fanartres>
                                              <imageres>540</imageres>
                                              <video>
                                                <busydialogdelayms>750</busydialogdelayms>
                                              </video>
                                              <samba>
                                                <clienttimeout>30</clienttimeout>
                                              </samba>
                                              <network>
                                                <readbufferfactor>4.0</readbufferfactor>
                                              </network>
                                            </advancedsettings>
00:00:08   8.521030 T:1967697920  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
00:00:08   8.521137 T:1967697920  NOTICE: Default DVD Player: dvdplayer
00:00:08   8.521198 T:1967697920  NOTICE: Default Video Player: dvdplayer
00:00:08   8.521256 T:1967697920  NOTICE: Default Audio Player: paplayer
00:00:08   8.521328 T:1967697920  NOTICE: Disabled debug logging due to GUI setting. Level 0.
00:00:08   8.521391 T:1967697920  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
00:00:08   8.521689 T:1967697920  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
00:00:08   8.525073 T:1967697920  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
00:00:08   8.527703 T:1967697920  NOTICE: Loaded playercorefactory configuration
00:00:08   8.528212 T:1967697920  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
00:00:08   8.528471 T:1967697920  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
00:00:08   8.568978 T:1957688384  NOTICE: Thread ActiveAE start, auto delete: false
00:00:08   8.569472 T:1947202624  NOTICE: Thread AESink start, auto delete: false
00:00:08   8.580132 T:1886385216  NOTICE: Thread CRBPWorker start, auto delete: false
00:00:08   8.677987 T:1967697920  NOTICE: Running database version Addons19
00:00:08   8.947515 T:1967697920  NOTICE: ADDONS: Using repository repository.xbmc.org
00:00:08   8.947696 T:1967697920  NOTICE: ADDONS: Using repository repository.openelec.tv
00:00:08   8.947766 T:1967697920  NOTICE: ADDONS: Using repository repository.unofficial.addon.pro
00:00:08   8.947826 T:1967697920  NOTICE: ADDONS: Using repository repository.simplycaz
00:00:08   8.948208 T:1875899456  NOTICE: Thread RemoteControl start, auto delete: false
00:00:09   9.018639 T:1967697920  NOTICE: Raspberry PI firmware version: Feb 19 2016 19:53:38
                                            Copyright (c) 2012 Broadcom
                                            version 573126451d3fb80e6de5ffb7d1fa117d814417b8 (clean) (release)
00:00:09   9.018821 T:1967697920  NOTICE: ARM mem: 848MB GPU mem: 160MB MPG2:0 WVC1:0
00:00:09   9.018889 T:1967697920  NOTICE: cacheMemBufferSize: 20MB
00:00:09   9.019359 T:1967697920  NOTICE: Config:
                                            arm_freq=900
                                            audio_pwm_mode=1
                                            audio_sdm_mod_order=2
                                            config_hdmi_boost=5
                                            disable_commandline_tags=2
                                            disable_l2cache=1
                                            disable_splash=1
                                            emmc_pll_core=1
                                            force_eeprom_read=1
                                            force_pwm_open=1
                                            framebuffer_ignore_alpha=1
                                            framebuffer_swap=1
                                            hdmi_channel_map=8
                                            hdmi_force_cec_address=65535
                                            hdmi_force_hotplug=1
                                            hdmi_ignore_cec_init=1
                                            init_uart_clock=0x2dc6c0
                                            lcd_framerate=60
                                            over_voltage_avs=0x1b774
                                            overscan_bottom=64
                                            overscan_left=72
                                            overscan_right=72
                                            overscan_top=64
                                            pause_burst_frames=1
                                            program_serial_random=1
                                            sdram_freq=450
                                            second_boot=1
                                            temp_limit=85
00:00:09   9.019606 T:1967697920  NOTICE: Config:
                                            device_tree=-
00:00:09   9.019716 T:1967697920  NOTICE: InitWindowSystem: Using EGL Implementation: raspberrypi
00:00:09   9.022080 T:1967697920  NOTICE: Found resolution 640 x 480 for display 0 with 640 x 480 @ 60.000000 Hz
00:00:09   9.022222 T:1967697920  NOTICE: Found resolution 640 x 480 for display 0 with 640 x 480 @ 59.940063 Hz
00:00:09   9.022296 T:1967697920  NOTICE: Found resolution 720 x 480 for display 0 with 720 x 480 @ 60.000000 Hz
00:00:09   9.022367 T:1967697920  NOTICE: Found resolution 720 x 480 for display 0 with 720 x 480 @ 59.940063 Hz
00:00:09   9.022434 T:1967697920  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 60.000000 Hz
00:00:09   9.022503 T:1967697920  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 59.940063 Hz
00:00:09   9.022571 T:1967697920  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 60.000000 Hz
00:00:09   9.022639 T:1967697920  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 59.940063 Hz
00:00:09   9.022706 T:1967697920  NOTICE: Found resolution 720 x 576 for display 0 with 720 x 576 @ 50.000000 Hz
00:00:09   9.022772 T:1967697920  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 50.000000 Hz
00:00:09   9.022839 T:1967697920  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 50.000000 Hz
00:00:09   9.022905 T:1967697920  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 24.000000 Hz
00:00:09   9.022972 T:1967697920  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 23.976025 Hz
00:00:09   9.023039 T:1967697920  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 25.000000 Hz
00:00:09   9.023106 T:1967697920  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 30.000000 Hz
00:00:09   9.023173 T:1967697920  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 29.970032 Hz
00:00:09   9.023237 T:1967697920  NOTICE: Found (1920x1080@60.000000) at 22, setting to RES_DESKTOP at 16
00:00:09   9.023429 T:1967697920  NOTICE: Checking resolution 16
00:00:09   9.141545 T:1967697920  NOTICE: GL_VENDOR = Broadcom
00:00:09   9.141737 T:1967697920  NOTICE: GL_RENDERER = VideoCore IV HW
00:00:09   9.141811 T:1967697920  NOTICE: GL_VERSION = OpenGL ES 2.0
00:00:09   9.141871 T:1967697920  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
00:00:09   9.142010 T:1967697920  NOTICE: GL_EXTENSIONS = GL_OES_compressed_ETC1_RGB8_texture GL_OES_compressed_paletted_texture GL_OES_texture_npot GL_OES_depth24 GL_OES_vertex_half_float GL_OES_EGL_image GL_OES_EGL_image_external GL_EXT_discard_framebuffer GL_OES_rgb8_rgba8 GL_OES_depth32 GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_APPLE_rgb_422 GL_EXT_debug_marker
00:00:10  10.002808 T:1967697920  NOTICE: Register - new cec device registered on cec->RPI: CEC Adapter (2708:1001)
00:00:10  10.003024 T:1856664640  NOTICE: Thread CECAdapter start, auto delete: false
00:00:10  10.042451 T:1831498816  NOTICE: Thread PeripBusUSBUdev start, auto delete: false
00:00:10  10.075135 T:1967697920  NOTICE: Running database version Addons19
00:00:10  10.079682 T:1967697920  NOTICE: Running database version ViewModes6
00:00:10  10.108649 T:1967697920  NOTICE: Running database version Textures13
00:00:10  10.128063 T:1967697920  NOTICE: Running database version MyMusic52
00:00:10  10.209443 T:1967697920  NOTICE: Running database version MyVideos93
00:00:10  10.216726 T:1967697920  NOTICE: Running database version TV29
00:00:10  10.221655 T:1967697920  NOTICE: Running database version Epg10
00:00:10  10.222066 T:1967697920  NOTICE: start dvd mediatype detection
00:00:10  10.222426 T:1958851648  NOTICE: Thread DetectDVDMedia start, auto delete: false
00:00:11  11.281306 T:1822307392  NOTICE: Thread CECAdapterUpdate start, auto delete: false
00:00:11  11.525450 T:1967697920 WARNING: JSONRPC: Could not parse type "PVR.Details.Channel"
00:00:11  11.526221 T:1967697920 WARNING: JSONRPC: Could not parse type "PVR.Details.ChannelGroup.Extended"
00:00:11  11.552039 T:1967697920 WARNING: JSONRPC: Could not parse type "GUI.Property.Value"
00:00:11  11.564349 T:1967697920 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
00:00:11  11.685931 T:1813918784  NOTICE: Thread LanguageInvoker start, auto delete: false
00:00:11  11.701415 T:1967697920  NOTICE: Previous line repeats 1 times.
00:00:11  11.701628 T:1967697920  NOTICE: initialize done
00:00:11  11.701729 T:1967697920  NOTICE: Running the application...
00:00:12  12.007876 T:1813918784  NOTICE: -->Python Interpreter Initialized<--
00:00:12  12.242321 T:1793061952  NOTICE: Thread JobWorker start, auto delete: true
00:00:12  12.338318 T:1967697920  NOTICE: starting zeroconf publishing
00:00:12  12.338803 T:1967697920  NOTICE: Webserver: Starting...
00:00:12  12.340156 T:1771287616  NOTICE: Thread JobWorker start, auto delete: true
00:00:12  12.340427 T:1967697920  NOTICE: WebServer: Started the webserver
00:00:12  12.340896 T:1967697920  NOTICE: starting upnp client
00:00:12  12.341369 T:1746121792  NOTICE: Thread JobWorker start, auto delete: true
00:00:12  12.353994 T:1967697920  NOTICE: ES: Starting event server
00:00:12  12.356642 T:1704178752  NOTICE: Thread EventServer start, auto delete: false
00:00:12  12.356991 T:1704178752  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
00:00:12  12.359101 T:1704178752  NOTICE: UDP: Listening on port 9777
00:00:12  12.375771 T:1653847104  NOTICE: Thread AirPlayServer start, auto delete: false
00:00:12  12.382668 T:1695790144  NOTICE: Thread TCPServer start, auto delete: false
00:00:12  12.429096 T:1958851648  NOTICE: Thread RSSReader start, auto delete: false
00:00:13  13.741147 T:1805530176  NOTICE: -->Python Interpreter Initialized<--
00:00:14  14.168059 T:1805530176  NOTICE: ## OpenELEC Addon ## 0.6.12
00:00:14  14.439158 T:1958851648   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
00:00:14  14.439435 T:1958851648   ERROR: CCurlFile::Open failed with code 0 for http://feeds.openelec.tv/news
00:00:21  21.448896 T:1958851648   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
00:00:21  21.449211 T:1958851648   ERROR: CCurlFile::Open failed with code 0 for http://feeds.openelec.tv/news
00:00:28  28.453693 T:1958851648   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
00:00:28  28.454006 T:1958851648   ERROR: CCurlFile::Open failed with code 0 for http://feeds.openelec.tv/news
00:00:28  28.454233 T:1958851648   ERROR: Unable to obtain rss feed: http://feeds.openelec.tv/news
00:02:46 166.968292 T:1793061952  NOTICE: Thread BackgroundLoader start, auto delete: false
00:02:50 170.507385 T:1793061952  NOTICE: Thread JobWorker start, auto delete: true
00:02:50 170.546646 T:1793061952   ERROR: SMBDirectory->GetDirectory: Unable to open directory : 'smb://USERNAME:PASSWORD@10.0.0.10/TV'
                                            unix_err:'d' error : 'Permission denied'
00:03:10 190.013809 T:1793061952   ERROR: Previous line repeats 1 times.
00:03:10 190.014099 T:1793061952   ERROR: SMBDirectory->GetDirectory: Unable to open directory : 'smb://USERNAME@10.0.0.10/TV'
                                            unix_err:'d' error : 'Permission denied'
00:03:13 193.516907 T:1967697920   ERROR: Previous line repeats 2 times.
00:03:13 193.517136 T:1967697920   ERROR: GetDirectory - Error getting smb://10.0.0.10/TV/
00:03:13 193.520645 T:1967697920   ERROR: CGUIMediaWindow::GetDirectory(smb://10.0.0.10/TV/) failed
00:03:13 193.569275 T:1620292672  NOTICE: Thread BackgroundLoader start, auto delete: false
00:03:38 218.118210 T:1793061952  NOTICE: Previous line repeats 1 times.
00:03:38 218.118454 T:1793061952   ERROR: CAddonInstallJob[plugin.video.crunchyroll]: dependency check failed

**Comment by davidkna** [comment]
You appear to be running Kodi 15.2. The minimum supported version by this addon is Kodi 17.

**Comment by AJRubenstein** [comment]
Well I feel right silly. I kept seeing the ticker down the bottom and thinking it was Kodi 18. My apologies.

**Comment by AJRubenstein** [comment]
Now I have a new problem. :)

I could install the add-on, put in all my details, and I'm getting a similar error. Here's the log.

                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 1241, in https_open
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 1198, in do_open
                                            URLError: <urlopen error [SSL: CERTI                                            FICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
07:53:44.591 T:1561240480   ERROR: ## OpenELEC Addon ## system::check_updates_v2                                             ## ERROR: (TypeError('expected string or buffer',))
07:53:44.592 T:1561240480   ERROR: Traceback (most recent call last):
                                              File "/home/stephan/projects/opene                                            lec-8.0.git/build.OpenELEC-RPi2.arm-8.0.4/OpenELEC-settings-0.8.1/.install_pkg/u                                            sr/share/kodi/addons/service.openelec.settings/resources/lib/modules/system.py",                                             line 538, in check_updates_v2
                                              File "/usr/lib/python2.7/json/__in                                            it__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/deco                                            der.py", line 364, in decode
                                            TypeError: expected string or buffer
07:54:02.650 T:1519297440   ERROR: CAddonInstallJob[resource.language.szl]: MD5                                             mismatch after download. Expected cedb1d29dd3bcbf7956289af10f1b177, was
07:54:09.441 T:1486877600   ERROR: CAddonInstallJob[resource.language.es_ar]: MD                                            5 mismatch after download. Expected ae01138de38ba37485e7422079487381, was
07:54:17.280 T:1505743776   ERROR: CAddonInstallJob[resource.language.be_by]: MD                                            5 mismatch after download. Expected 4cc0dba443cf1c6285075dfd2fd6a602, was
07:54:51.839 T:1544463264   ERROR: GetDirectory - Error getting
07:55:46.400 T:1946841104   ERROR: Previous line repeats 2 times.
07:55:46.401 T:1946841104  NOTICE: Samba is idle. Closing the remaining connecti                                            ons
07:56:57.225 T:1505743776 WARNING: COMXImageFile::GetCodingType progressive imag                                            es not supported by decoder
07:56:57.226 T:1505743776 WARNING: Previous line repeats 1 times.
07:56:57.226 T:1505743776  NOTICE: LoadJpeg: unable to load /storage/.kodi/addon                                            s/plugin.video.youtube/fanart.jpg
07:56:58.007 T:1505743776 WARNING: COMXImageFile::GetCodingType progressive imag                                            es not supported by decoder
07:56:58.010 T:1505743776 WARNING: Previous line repeats 1 times.
07:56:58.010 T:1505743776  NOTICE: LoadJpeg: unable to load /storage/.kodi/addon                                            s/plugin.video.crunchyroll/fanart.jpg
07:57:00.404 T:1505743776   ERROR: GetDirectory - Error getting
08:00:58.280 T:1440740256   ERROR: Previous line repeats 6 times.
08:00:58.280 T:1440740256   ERROR: EXCEPTION Thrown (PythonToCppException) : -->                                            Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO M                                            EMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError                                            '>
                                            Error Contents: <urlopen error [SSL:                                             CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin                                            .video.crunchyroll/default.py", line 33, in <module>
                                                crunchyroll.main(sys.argv)
                                              File "/storage/.kodi/addons/plugin                                            .video.crunchyroll/resources/lib/crunchyroll.py", line 90, in main
                                                if api.start(args):
                                              File "/storage/.kodi/addons/plugin                                            .video.crunchyroll/resources/lib/api.py", line 79, in start
                                                req = request(args, "start_sessi                                            on", payload, True)
                                              File "/storage/.kodi/addons/plugin                                            .video.crunchyroll/resources/lib/api.py", line 156, in request
                                                response = urlopen(url, payload.                                            encode("utf-8"))
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 429, in open
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 447, in _open
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 1241, in https_open
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 1198, in do_open
                                            URLError: <urlopen error [SSL: CERTI                                            FICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
                                            -->End of Python script error report                                            <--
08:00:58.446 T:1946841104   ERROR: GetDirectory - Error getting plugin://plugin.                                            video.crunchyroll/?title=You%20need%20to%20be%20logged%20in
08:00:58.448 T:1946841104   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin                                            .video.crunchyroll/?title=You%20need%20to%20be%20logged%20in) failed
08:01:02.093 T:1461711776   ERROR: Unable to find plugin
08:01:02.093 T:1946841104   ERROR: GetDirectory - Error getting plugin://
08:01:02.095 T:1946841104   ERROR: CGUIMediaWindow::GetDirectory(plugin://) fail                                            ed
08:01:13.229 T:1946841104   ERROR: Control 55 in window 10025 has been asked to                                             focus, but it can't
08:01:14.482 T:1432351648   ERROR: EXCEPTION Thrown (PythonToCppException) : -->                                            Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO M                                            EMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError                                            '>
                                            Error Contents: <urlopen error [SSL:                                             CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin                                            .video.crunchyroll/default.py", line 33, in <module>
                                                crunchyroll.main(sys.argv)
                                              File "/storage/.kodi/addons/plugin                                            .video.crunchyroll/resources/lib/crunchyroll.py", line 90, in main
                                                if api.start(args):
                                              File "/storage/.kodi/addons/plugin                                            .video.crunchyroll/resources/lib/api.py", line 79, in start
                                                req = request(args, "start_sessi                                            on", payload, True)
                                              File "/storage/.kodi/addons/plugin                                            .video.crunchyroll/resources/lib/api.py", line 156, in request
                                                response = urlopen(url, payload.                                            encode("utf-8"))
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 429, in open
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 447, in _open
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 1241, in https_open
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 1198, in do_open
                                            URLError: <urlopen error [SSL: CERTI                                            FICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
                                            -->End of Python script error report                                            <--
08:01:14.649 T:1946841104   ERROR: GetDirectory - Error getting plugin://plugin.                                            video.crunchyroll/
08:01:14.652 T:1946841104   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin                                            .video.crunchyroll/) failed
08:03:03.253 T:1552851872   ERROR: EXCEPTION Thrown (PythonToCppException) : -->                                            Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO M                                            EMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError                                            '>
                                            Error Contents: <urlopen error [SSL:                                             CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin                                            .video.crunchyroll/default.py", line 33, in <module>
                                                crunchyroll.main(sys.argv)
                                              File "/storage/.kodi/addons/plugin                                            .video.crunchyroll/resources/lib/crunchyroll.py", line 90, in main
                                                if api.start(args):
                                              File "/storage/.kodi/addons/plugin                                            .video.crunchyroll/resources/lib/api.py", line 79, in start
                                                req = request(args, "start_sessi                                            on", payload, True)
                                              File "/storage/.kodi/addons/plugin                                            .video.crunchyroll/resources/lib/api.py", line 156, in request
                                                response = urlopen(url, payload.                                            encode("utf-8"))
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 429, in open
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 447, in _open
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 1241, in https_open
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 1198, in do_open
                                            URLError: <urlopen error [SSL: CERTI                                            FICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
                                            -->End of Python script error report                                            <--
08:03:03.422 T:1946841104   ERROR: GetDirectory - Error getting plugin://plugin.                                            video.crunchyroll/
08:03:03.425 T:1946841104   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin                                            .video.crunchyroll/) failed
08:04:14.117 T:1915745184  NOTICE: CAESinkPi:AddPackets Underrun (delay:0.00 fra                                            mes:2205)
08:06:05.448 T:1946841104   ERROR: Control 55 in window 10025 has been asked to                                             focus, but it can't
08:06:06.709 T:1388311456   ERROR: EXCEPTION Thrown (PythonToCppException) : -->                                            Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO M                                            EMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError                                            '>
                                            Error Contents: <urlopen error [SSL:                                             CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin                                            .video.crunchyroll/default.py", line 33, in <module>
                                                crunchyroll.main(sys.argv)
                                              File "/storage/.kodi/addons/plugin                                            .video.crunchyroll/resources/lib/crunchyroll.py", line 90, in main
                                                if api.start(args):
                                              File "/storage/.kodi/addons/plugin                                            .video.crunchyroll/resources/lib/api.py", line 79, in start
                                                req = request(args, "start_sessi                                            on", payload, True)
                                              File "/storage/.kodi/addons/plugin                                            .video.crunchyroll/resources/lib/api.py", line 156, in request
                                                response = urlopen(url, payload.                                            encode("utf-8"))
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 429, in open
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 447, in _open
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 1241, in https_open
                                              File "/usr/lib/python2.7/urllib2.p                                            y", line 1198, in do_open
                                            URLError: <urlopen error [SSL: CERTI                                            FICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
                                            -->End of Python script error report                                            <--
08:06:06.881 T:1946841104   ERROR: GetDirectory - Error getting plugin://plugin.                                            video.crunchyroll/
08:06:06.883 T:1946841104   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin                                            .video.crunchyroll/) failed

**Comment by MrKrabat** [comment]
1. OpenELEC is outdated and no longer under development (as far as I know)
You might want to check LibreELEC :)

2. "certificate verify failed", there are plenty reasons why this happens.
I think switching to LibreELEC will fix this as well. Probably your system time is just wrong (this happens often on devices like a raspberry pi without a real time clock).

**Comment by AJRubenstein** [comment]
Thank you so much for your help. After much tearing of hair I did eventually work out how to update OpenElec to LibreELEC - and it did indeed fix my problem. Your app is working beautifully - ironically much better than any of the Crunchyroll apps. Truly, you are doing the work of kings. I cannot tell you how much I appreciate this little add-on, and your support. :)
