### ISSUE TITLE
Control 55 in window 10025 has been asked to focus, but it can't

### ISSUE THREAD

**Issue by AJRubenstein** [MrKrabat/plugin.video.crunchyroll#16]
Hey again,

Plugin has been working beautifully for months - and now we've had a new random issue - I'm hoping that Crunchyroll hasn't prevented access. 

So as to not waste too much time, I've tried reinstalling both LibreElec, Kodi and the plugin just in case they're the issue. But here's the main part of the log that seems to be the issue:

11:19:05.365 T:1937013136   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
11:19:07.441 T:1555018608   ERROR: Unable to find plugin
11:19:07.441 T:1555018608   ERROR: GetDirectory - Error getting plugin://
11:19:07.443 T:1937013136   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed

Everything I've read seems to suggest it's got something to do with them checking for the User Agent in http requests? But I couldn't figure out where to go next.

Cheers.

**Comment by AJRubenstein** [comment]
Reinstalled everything... again. Hard reset this time. It works now. Sorry about the trouble.

**Comment by JTVesagie** [comment]
hi guys . got the exact same error on 19.4 windows . did you get a solution besides re installing. that didnt work for me
