### ISSUE TITLE
Please add a "add to Libary" Feature

### ISSUE THREAD

**Issue by Mark2964** [MrKrabat/plugin.video.crunchyroll#17]
Hello,

first: Its a great pluging. Great work. Perfekt for a mediacenter-PC.

second: Please add a "add to Libary" Feature. Similar to the Netflix and Amazon VOD plugin. in the  Amazon and Netflix plugins can export to a path on a Harddrive. It is a .strm-File. into the strm-file is a Link to the Video-URL. The plugin would get even better.

strm ist compactible with this plugin. I have made a few strm-file and it works with the plugin. But I must made it by myself.

**Comment by tatsumasagc** [comment]
@Mark2964 how did you make the strm-file?

**Comment by MrKrabat** [comment]
I think it is easier to use an addon for this.

There is a addon called "STRM Generator" (not in the official Kodi repository) which adds a context menu entry for creating strm files. This applies to every addon. Much easier than asking every addon creator to add such a feature.

**Comment by tatsumasagc** [comment]
I got the strm generator, unfortunately the strm files it creates for videos in this addon only work on the device it was created on. I.e. I create it on kodi for windows x64, the strm file doesn't work on my kodi for android

**Comment by MrKrabat** [comment]
is the crunchyroll addon installed and working on your android device?
The strm file still requires the crunchyroll addon for playback.

**Comment by tatsumasagc** [comment]
Yes Crunchyroll addon is installed on both

On 2 Jul 2019 20:31, MrKrabat <notifications@github.com> wrote:

is the crunchyroll addon installed and working on your android device?
The strm file still requires the crunchyroll addon for playback.
