### ISSUE TITLE
join efforts with other chrunchyroll dev?

### ISSUE THREAD

**Issue by MartijnKaijser** [MrKrabat/plugin.video.crunchyroll#2]
@Yoshiofthewire has been maintaining this addon for a long time already and perhaps you could join efforts to getting a good supported plugin?
Just a though

https://github.com/Yoshiofthewire/CrunchyXBMC/

That would give us as team kodi a good repo version as well.

**Comment by MrKrabat** [comment]
My plan was to ask @Yoshiofthewire if i can take over this addon, since he mentioned he is not using Crunchyroll anymore.

Thats why i did rewrite it, especially to fix playback issues with help of inputstream.adaptive and to include python 3 support.

**Comment by cognitiaclaeves** [comment]
Out of curiosity, have you asked @yoshiofthewire to take over this plugin?

**Comment by MrKrabat** [comment]
Well, I guess since the addon got DMCA'd we can close this.

I will try to contact Crunchyroll and ask for permissions to use their API.
I hope the [shitstorm they created](https://torrentfreak.com/crunchyroll-addon-for-kodi-hit-with-fatal-copyright-complaint-180613/) will help to convince them :)
