### ISSUE TITLE
Audio stream claims to contain 0 audio channels

### ISSUE THREAD

**Issue by NCLI** [MrKrabat/plugin.video.crunchyroll#22]
The video plays just fine, but the audio stream is reported as having 0 channels. Therefore, if Kodi's "Output configuration" is set as anything other than "fixed", no audio will be played.

All other streaming add-ons work just fine, including ones using InputStream Adaptive, as does regular video playback.

**Comment by MrKrabat** [comment]
Probably an encoding error from Crunchyroll? Or some kind of incompatibility with InputStream Adaptive?

I'm sorry but there is nothing I can do, as this addon only passes the stream url to InputStream Adaptive.

**Comment by MrKrabat** [comment]
Closed, as there was no further communication
