### ISSUE TITLE
Can't install on kodi 19

### ISSUE THREAD

**Issue by C4ET4uK** [MrKrabat/plugin.video.crunchyroll#27]
When trying to install on kodi 19 got error
The dependency on xbmc.python version 2.25.0 could not be satisfied.

**Comment by MrKrabat** [comment]
Kodi 19 is not backwards compatible with addons made for previous versions.
I need to create a second addon version for kodi 19.

**Comment by fagnerpatricio** [comment]
Do You have Plans for this?

**Comment by MrKrabat** [comment]
Since Kodi 19 is still an alpha version, this update is not important.

You can download and install from this branch matrix:
https://github.com/MrKrabat/plugin.video.crunchyroll/tree/matrix

**Comment by fagnerpatricio** [comment]
Thank You :D
