### ISSUE TITLE
Unable to View Queue

### ISSUE THREAD

**Issue by the0remora** [MrKrabat/plugin.video.crunchyroll#28]
When I try to open my queue I get the notification "Crunchroll Error: Check logfile" I have 66 items in my queue. The plugin plays videos fine if I go to the "Anime" item although that is not in this logfile. I am running CoreELEC 9.2.4 (Kodi 18.8).

My logfile is uploaded here: [http://ix.io/2u7h](http://ix.io/2u7h)

**Comment by MrKrabat** [comment]
This was probably a problem of Crunchyroll and should work again. If not, please reopen.
