### ISSUE TITLE
Trakt.tv

### ISSUE THREAD

**Issue by GamerClassN7** [MrKrabat/plugin.video.crunchyroll#33]
Would be possible to add trakt.tv support ?

**Comment by GameBoyYeet** [comment]
im not @MrKrabat, but this plugin is for crunchyroll, so maybe look somewhere else

**Comment by GamerClassN7** [comment]
@GameBoyYeet  do you know what Trakt.tv is ? i rally change platform really often so it is better for me to have my watch status synchronized between them, regarding many platform netflix, crunchyroll, cartoonamnia so i did not watch same title again and again

**Comment by steewel** [comment]
That would indeed be awesome, if just scrobble was an option I would be really grateful

**Comment by MrKrabat** [comment]
I'm not a fan of adding support for third-party things.
It's a lot of work and then people ask for a lot of different third-party integrations.

This addon should synchronize your progress with Crunchyroll servers and retrieve your progress from them.
