### ISSUE TITLE
Failure in Kodi 19

### ISSUE THREAD

**Issue by lucaskercher** [MrKrabat/plugin.video.crunchyroll#38]
Failure caused by the xbmc.python addon.

Solution: https://github.com/xbmc/xbmc/issues/17326

**Comment by robofunk** [comment]
This is the Matrix compatible version of the add-on https://github.com/MrKrabat/plugin.video.crunchyroll/tree/matrix .

**Comment by lucaskercher** [comment]
Thank you for the link!
