### ISSUE TITLE
the dependency on xbmc.python version 2.25.0 could not be satisfied

### ISSUE THREAD

**Issue by TheSlimerX** [MrKrabat/plugin.video.crunchyroll#48]
I've installed the new Kodi 19 version and tried to install this addon from a zip but this error message came up.

**Comment by robofunk** [comment]
Download the updated version https://github.com/MrKrabat/plugin.video.crunchyroll/archive/refs/heads/matrix.zip

**Comment by leogcurvelo** [comment]
This happened to me as well.
Have you considered changing the default branch to the matrix one, or merge it to master?
