### ISSUE TITLE
Unable to see episodes in queue

### ISSUE THREAD

**Issue by cognitiaclaeves** [MrKrabat/plugin.video.crunchyroll#5]
I seem to be having issues seeing which episodes are in a queued show. I know in the official app, there's a screen I can access that shows how far I've watched each episode. (Though it might not be directly from the queue interface.)

Sometimes, I want to be able to choose which episode to watch in a queued show. Is there a way to access this now? One of the screenshots in the project implies that there is.

Thanks!

**Comment by MrKrabat** [comment]
When you view your queue, you can press the 'C' key on a keyboard to open a context menu. There you can choose to jump to the season or episode overview.

The screenshots are from another addon I maintain. I forgot to change them.
But this overview exists here too if you navigate to to the anime for example with the search function.
