### ISSUE TITLE
Not working Windows

### ISSUE THREAD

**Issue by Respectme** [MrKrabat/plugin.video.crunchyroll#6]
Hello there, I have been getting this problem for quite sometime now
So please help me fix it 

> \u063a\u064a\u0631 \u0635\u062d\u064a\u062d\u0629.', u'code': u'object_not_found', u'error': True}'
04:28:43.874 T:2976   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.WindowsError'>
                                            Error Contents: (2, 'The system cannot find the file specified', u'C:\\Users\\ADSL\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.video.crunchyroll\\cookies.lwp')
                                            Traceback (most recent call last):
                                              File "C:\**\**\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll\default.py", line 35, in <module>
                                                crunchyroll.main()
                                              File "C:\**\**\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll\resources\lib\crunchyroll.py", line 108, in main
                                                if api.start(args):
                                              File "C:\**\**\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll\resources\lib\api.py", line 88, in start
                                                req = request(args, "login", payload, True)
                                              File "C:\**\**\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll\resources\lib\api.py", line 168, in request
                                                destroy(args)
                                              File "C:\**\**\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll\resources\lib\api.py", line 129, in destroy
                                                remove(getCookiePath(args))
                                            WindowsError: (2, 'The system cannot find the file specified', u'C:\\Users\\ADSL\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.video.crunchyroll\\cookies.lwp')
                                            -->End of Python script error report<--
04:28:43.968 T:5356   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.crunchyroll/
04:28:43.968 T:5356   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.crunchyroll/) failed
04:30:21.030 T:3912 WARNING: CSkinInfo: failed to load skin settings
04:30:53.920 T:4756 WARNING: CWin32DirectSound::GetSpace - buffer underrun - W:21888, P:8656, O:21152.
04:30:57.669 T:4756 WARNING: CWin32DirectSound::GetSpace - buffer underrun - W:12312, P:62240, O:11312.
04:31:12.772 T:7552   ERROR: CFFmpegImage::ExtractFrame: Could not decode a frame

**Comment by MrKrabat** [comment]
Hi, thanks for reporting this.
I added a patch to catch the exception if the session file does not exists, but I don't know if this will help.

Your addon files are located at "C:**\AppData\..." and the session file is located at "C:\Users\...".
This C:**\ looks a little bit strange to be, but maybe it is ok.

How often does this occur? Technically it should only happen after not using the addon for a few days, so that the session cannot be renewed

**Comment by Respectme** [comment]
C:**\ is the same C:\users 
i just edited it to hide names.

**Comment by MrKrabat** [comment]
Good, I'm glad it's working now :)
