### ISSUE TITLE
Subtitle Language set to none

### ISSUE THREAD

**Issue by TheScaryX** [MrKrabat/plugin.video.crunchyroll#66]
Is it possible to set subtitle language to none? Just in case I want to watch anime with unofficial fan made subtitles in my own language. Thanks in advance.

**Comment by smirgol** [comment]
In theory that should be possible as Crunchyroll seems to provide a base stream without subtitles - I have not tested that, but there is one without a language setting, which might be suitable. For that it would be required to add the different streams to the video stream selection that you have on every movie in kodi, but I honestly have no idea how to do that. Maybe someone else does?

**Comment by robofunk** [comment]
I have PR against the beta API to enable soft subtitles, which can then be disabled.

**Comment by smirgol** [comment]
Implemented as of #70 (Nexus) #71 (Matrix) and #72 (Leia)
