### ISSUE TITLE
video failed to load

### ISSUE THREAD

**Issue by Galnart** [MrKrabat/plugin.video.crunchyroll#67]
Version: Nexus 11.0.3

videos started to failed to load yesterday and haven't worked since.
Rebooting or reinstalling the addon has no effect.

**Comment by robofunk** [comment]
My fork works fine on the latest nightly for me. If you're on windows you should post your log %APPDATA%\Kodi\kodi.log .

https://github.com/robofunk/plugin.video.crunchyroll

**Comment by Galnart** [comment]
using librelec. but i saw the solution in the closed issue from hdet. i just needed to remove the login info and then log in again

**Comment by Galnart** [comment]
I will check out that fork
