### ISSUE TITLE
seasons/arcs missing from listing

### ISSUE THREAD

**Issue by crpb** [MrKrabat/plugin.video.crunchyroll#68]
Hi,

for a while now i noticed that some seasons/movies aren't listed.
as an example for this problem you might take a look at [That Time I Got Reincarnated as a Slime](https://www.crunchyroll.com/series/GYZJ43JMR/that-time-i-got-reincarnated-as-a-slime).
i was already missing the "Movie" since the release and the same goes now for the "Visions of Coleus" season.

screenshot from the website
![maim_20231116-095049](https://github.com/MrKrabat/plugin.video.crunchyroll/assets/5575140/91a28270-1c03-4624-8328-8ab7581e1db2)
screenshot from kodi
![screenshot00000](https://github.com/MrKrabat/plugin.video.crunchyroll/assets/5575140/e83ad395-2e89-4731-8ff0-d7ff53fffb9e)

i'm currently running #56 but that problem with the movie already occurred with the master branch so i don't think that the issue came up with that version.

if you could point me in the right direction to debug the problem i'm happy to take a crack at it with my low-level python skills :see_no_evil:.

```
osmc@osmc:~$ kodi --version
Kodi Media Center 20.2
Copyright (C) 2005-2021 Team Kodi - http://kodi.tv
osmc@osmc:~/.kodi/addons/plugin.video.crunchyroll$ git branch
* 56
  main
  master
```

**Comment by robofunk** [comment]
The movie isn't shown because Crunchyroll only has the subbed version and you are filtering out dubs. I don't know why Visions of Coleus isn't shown.

**Comment by crpb** [comment]
Hey, thanks for the quick reply.
The Movie should be available as ja-JP from the [info](https://www.crunchyroll.com/watch/GJWU2EQM4/) and from what i can _hear_ when i retrieve it with the help of [yt-dlp](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/crunchyroll.py) or with something like `mpv --ytdl-raw-options=cookies-from-browser=chromium https://www.crunchyroll.com/watch/GJWU2EQM4/`.

**Comment by robofunk** [comment]
I'm thinking this may be an issue with the old API, which the website and modern apps don't use.

**Comment by robofunk** [comment]
I have fixed this issue on my PR. By default the API would only return 30 results, I've increased it to 999. https://github.com/MrKrabat/plugin.video.crunchyroll/pull/56

**Comment by crpb** [comment]
Thank you!
